# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STlkEXgtwXfENUJyL0YRV8xJ9sq0JsN9
"""

texto = input('Digite algo: ')
print('É alfabético?', texto.isalpha())
print('É numero?', texto.isnumeric())
print("Só tem espaços?", texto.isspace())
print("É alfanumérico?", texto.isalnum())
print("Está em maiúsculas?", texto.isupper())
print("Está em minúsculas?", texto.islower())
print("Está em formato título?", texto.istitle())